// HOTFIX v2.4: robust startup and Three.js r128 compatibility
class Game {
  constructor() { this.scene = null; this.camera = null; this.renderer = null; this.player = null; this.enemies = []; this.items = []; this.doors = {}; this.puzzles = []; this.checkpoints = []; this.currentCheckpoint = 0; this.isGameActive = false; this.isPaused = false; this.gameTime = 0; this.playTime = 0; this.input = { keys: {} }; this.lastTime = performance.now(); this.init(); this.setupEventListeners(); }
  init() {
    try {
      puzzleManager = new PuzzleManager(this); storyManager = new StoryManager(this); jumpScareManager = new JumpScareManager(this);
      this.scene = new THREE.Scene(); this.scene.background = new THREE.Color(GAME_CONFIG.fogColor);
      if (GAME_CONFIG.fogEnabled) this.scene.fog = new THREE.FogExp2(GAME_CONFIG.fogColor, GAME_CONFIG.fogDensity);
      this.camera = new THREE.PerspectiveCamera(75, innerWidth / innerHeight, .1, 1000);
      this.renderer = new THREE.WebGLRenderer({ canvas: document.getElementById('game-canvas'), antialias: true }); this.renderer.setSize(innerWidth, innerHeight); this.renderer.shadowMap.enabled = !!GAME_CONFIG.shadowEnabled;
      this.scene.add(new THREE.AmbientLight(0x333333, .35)); this.createLaboratory(); this.player = new Player(this.scene, 0, 0); this.camera.position.copy(this.player.mesh.position); this.createEnemies(); this.createItems(); this.createPuzzles(); this.checkpoints = [{x:0,y:1.7,z:0},{x:0,y:1.7,z:-40},{x:30,y:1.7,z:-40},{x:30,y:1.7,z:-80},{x:-30,y:1.7,z:-80},{x:0,y:1.7,z:-100}]; this.animate();
    } catch (error) { console.error('Game initialization failed:', error); }
    const loading = document.getElementById('loading-screen'), menu = document.getElementById('main-menu'); if (loading) loading.hidden = true; if (menu) menu.hidden = false;
  }
  createLaboratory() { const floor = new THREE.Mesh(new THREE.PlaneGeometry(200,200), new THREE.MeshStandardMaterial({color:0x2a2a2a,roughness:.85})); floor.rotation.x=-Math.PI/2; this.scene.add(floor); const wallMat=new THREE.MeshStandardMaterial({color:0x3a3a3a}); [{x:-100,z:0,w:2,h:6,d:200},{x:100,z:0,w:2,h:6,d:200},{x:0,z:-100,w:200,h:6,d:2},{x:0,z:100,w:200,h:6,d:2},{x:-20,z:-20,w:2,h:6,d:40},{x:20,z:-20,w:2,h:6,d:40},{x:-60,z:-50,w:80,h:6,d:2},{x:60,z:-70,w:80,h:6,d:2}].forEach(p=>{const w=new THREE.Mesh(new THREE.BoxGeometry(p.w,p.h,p.d),wallMat);w.position.set(p.x,3,p.z);this.scene.add(w);}); [{x:0,z:-20},{x:0,z:-60},{x:-40,z:-40},{x:40,z:-40},{x:0,z:-90}].forEach(p=>{const l=new THREE.PointLight(0xffaa00,1.2,20);l.position.set(p.x,5,p.z);this.scene.add(l);}); }
  createEnemies() { this.enemies.push(new Enemy(this.scene,0,-30,'basic',[{x:0,z:-20},{x:0,z:-40}])); this.enemies.push(new Enemy(this.scene,30,-50,'fast',[{x:25,z:-45},{x:35,z:-55}])); this.enemies.push(new Enemy(this.scene,-30,-70,'tank',[{x:-35,z:-65},{x:-25,z:-75}])); const stealth=new Enemy(this.scene,60,-85,'stealth',[{x:55,z:-80},{x:65,z:-90}]); stealth.deactivate(); this.enemies.push(stealth); const boss=new Enemy(this.scene,0,-95,'boss',[{x:-10,z:-90},{x:10,z:-100}]); boss.deactivate(); this.enemies.push(boss); }
  createItems() { [{x:-30,z:-30,t:'keycard',n:'Lab Keycard',i:'🔑'},{x:30,z:-50,t:'battery',n:'Battery',i:'🔋'},{x:-40,z:-70,t:'fuse',n:'Fuse',i:'⚡'},{x:0,z:-20,t:'medkit',n:'Medkit',i:'💊'},{x:30,z:-65,t:'sanity_potion',n:'Sanity Potion',i:'🧪'}].forEach(d=>this.items.push(new Item(this.scene,d.x,1,d.z,d.t,d.n,d.i))); }
  createPuzzles() { this.createDoors(); const p1=puzzleManager.createKeypadPuzzle(-20,2,-20,'7391','door_main'); const p2=puzzleManager.createColorPuzzle(30,2,-60,['red','blue','green'],'door_lab'); const p3=puzzleManager.createCollectionPuzzle(['keycard','battery','fuse'],'door_exit','Find all equipment'); this.puzzles.push(p1,p2,p3); }
  createDoors() { const mat=new THREE.MeshStandardMaterial({color:0x553333}); [{id:'door_main',x:-20,z:-20},{id:'door_lab',x:30,z:-60},{id:'door_exit',x:0,z:-105}].forEach(d=>{const m=new THREE.Mesh(new THREE.BoxGeometry(4,4.5,.4),mat);m.position.set(d.x,2.25,d.z);this.scene.add(m);this.doors[d.id]={mesh:m,open:false,initialX:d.x,initialY:2.25};}); }
  openDoor(id) { const d=this.doors[id]; if(!d||d.open)return; d.open=true; const timer=setInterval(()=>{if(id==='door_exit'){d.mesh.position.y+=.12;if(d.mesh.position.y>d.initialY+3.5)clearInterval(timer);}else{d.mesh.position.x+=.12;if(d.mesh.position.x>d.initialX+2.5)clearInterval(timer);}},16); }
  setupEventListeners() { addEventListener('keydown',e=>{this.input.keys[e.key.toLowerCase()]=true;if(e.key==='Escape'&&this.isGameActive)this.togglePause();if(e.key.toLowerCase()==='e')this.tryInteract();if(e.key==='Shift'&&this.player)this.player.isSprinting=true;}); addEventListener('keyup',e=>{this.input.keys[e.key.toLowerCase()]=false;if(e.key==='Shift'&&this.player)this.player.isSprinting=false;}); document.getElementById('btn-new-game')?.addEventListener('click',()=>this.startNewGame()); document.getElementById('btn-continue')?.addEventListener('click',()=>this.startNewGame()); document.getElementById('btn-pause')?.addEventListener('click',()=>this.togglePause()); document.getElementById('btn-resume')?.addEventListener('click',()=>this.togglePause()); document.getElementById('btn-main-menu')?.addEventListener('click',()=>this.showMainMenu()); document.getElementById('btn-save-game')?.addEventListener('click',()=>this.saveGame()); }
  startNewGame() { document.getElementById('main-menu').hidden=true; document.getElementById('game-container').hidden=false; this.isGameActive=true; this.player.setPosition(0,1.7,0); this.camera.position.copy(this.player.mesh.position); try { document.getElementById('game-canvas').requestPointerLock(); } catch(e) {} }
  togglePause() { this.isPaused=!this.isPaused; document.getElementById('pause-menu').hidden=!this.isPaused; if(this.isPaused) document.exitPointerLock(); }
  showMainMenu() { this.isGameActive=false; document.getElementById('game-container').hidden=true; document.getElementById('main-menu').hidden=false; }
  tryInteract() { if(!this.isGameActive||this.isPaused)return; this.items.forEach(item=>{if(!item.isCollected&&this.player.mesh.position.distanceTo(item.mesh.position)<2.5){const got=item.collect();if(got.type==='medkit')this.player.heal(50);else if(got.type==='sanity_potion')this.player.restoreSanity(40);else this.player.addToInventory(got);}}); this.puzzles.forEach(p=>{if(!puzzleManager.solvedPuzzles[p.id]&&puzzleManager.checkPuzzle(p,this.player)){if(p.type==='keypad')puzzleManager.showKeypadUI(p);else if(p.type==='color')puzzleManager.showColorUI(p);else if(p.type==='collection'&&puzzleManager.checkPuzzle(p,this.player))puzzleManager.solvePuzzle(p);}}); }
  update(dt) { if(!this.isGameActive||this.isPaused)return; this.gameTime+=dt;this.playTime+=dt;this.player.update(dt,this.input,this.camera,this.enemies);this.camera.position.copy(this.player.mesh.position);this.enemies.forEach(e=>e.update(dt,this.player));this.items.forEach(i=>i.update(dt,this.gameTime));if(this.player.isDead){this.isGameActive=false;document.getElementById('death-screen').hidden=false;}this.updateHUD(); }
  updateHUD() { const set=(id,value,text)=>{const e=document.getElementById(id);if(e)e.style.width=value+'%';const t=document.getElementById(text);if(t)t.textContent=Math.round(value)+'%';};set('health-fill',this.player.health,'health-text');set('stamina-fill',this.player.stamina,'stamina-text');const s=document.getElementById('sanity-fill');if(s)s.style.width=this.player.sanity+'%';const st=document.getElementById('sanity-text');if(st)st.textContent='SANITY: '+Math.round(this.player.sanity)+'%'; }
  saveGame() { try { SaveSystem.saveToLocal(this.getGameState()); } catch(e) { console.warn('Save failed',e); } }
  getGameState() { return {playTime:this.playTime,position:this.player.getPosition(),health:this.player.health,sanity:this.player.sanity,inventory:this.player.inventory}; }
  animate() { requestAnimationFrame(()=>this.animate());const now=performance.now();const dt=Math.min((now-this.lastTime)/1000,.05);this.lastTime=now;this.update(dt);if(this.renderer)this.renderer.render(this.scene,this.camera); }
}
window.addEventListener('load',()=>{window.game=new Game();});
