// v3.0 Mansion rebuild - playable first-person horror prototype
class Game {
  constructor() { this.scene=null; this.camera=null; this.renderer=null; this.player=null; this.enemies=[]; this.items=[]; this.walls=[]; this.doors={}; this.puzzles=[]; this.input={keys:{}}; this.isGameActive=false; this.isPaused=false; this.lastTime=performance.now(); this.init(); this.bindUI(); }
  init(){ try { puzzleManager=new PuzzleManager(this); storyManager=new StoryManager(this); jumpScareManager=new JumpScareManager(this); this.scene=new THREE.Scene(); this.scene.background=new THREE.Color(0x080a12); this.scene.fog=new THREE.FogExp2(0x080a12,.018); this.camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,300); this.renderer=new THREE.WebGLRenderer({canvas:document.getElementById('game-canvas'),antialias:true}); this.renderer.setSize(innerWidth,innerHeight); this.renderer.setPixelRatio(Math.min(devicePixelRatio,2)); this.renderer.shadowMap.enabled=true; this.scene.add(new THREE.HemisphereLight(0x7080aa,0x160b08,.45)); this.buildMansion(); this.player=new Player(this.scene,0,12); this.camera.position.copy(this.player.mesh.position); this.createItems(); this.createEnemies(); this.animate(); } catch(err) { console.error(err); } document.getElementById('loading-screen').hidden=true; document.getElementById('main-menu').hidden=false; }
  addBox(x,y,z,w,h,d,color=0x342923){ const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.82}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;this.scene.add(m);return m; }
  wall(x,z,w,d){const m=this.addBox(x,3,z,w,6,d,0x211914);this.walls.push({x:x-w/2,x2:x+w/2,z:z-d/2,z2:z+d/2});return m;}
  light(x,y,z,color=0xffbd72,intensity=2,range=18){const l=new THREE.PointLight(color,intensity,range,2);l.position.set(x,y,z);l.castShadow=true;this.scene.add(l);return l;}
  buildMansion(){ const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:0x30251e,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;this.scene.add(floor); this.wall(0,-45,80,2);this.wall(0,45,80,2);this.wall(-40,0,2,90);this.wall(40,0,2,90); this.wall(-22,8,2,44); this.wall(22,8,2,44); this.wall(0,-12,44,2); this.wall(-12,-30,2,34);this.wall(12,-30,2,34);this.wall(0,-47,28,2); this.wall(-25,-27,28,2);this.wall(25,-27,28,2); this.wall(-28,-5,20,2);this.wall(28,-5,20,2); this.addBox(0,1.1,7,10,2.2,6,0x4d3626); this.addBox(0,2.7,2,7,1.2,4,0x5b412e); for(let i=0;i<7;i++){this.addBox(-33,2,-30+i*7,2,4,4,0x291d16);this.addBox(33,2,-30+i*7,2,4,4,0x291d16);} this.addBox(-28,1,-9,9,2,3,0x482f23);this.addBox(28,1,-9,9,2,3,0x482f23); this.addBox(0,1,-33,13,2,4,0x4d3424);this.addBox(0,3.3,-41,10,2,1,0x1c1715); [[0,5,15],[0,5,-4],[-28,5,-15],[28,5,-15],[0,5,-34],[-25,5,-39],[25,5,-39]].forEach((p,i)=>{const l=this.light(p[0],p[1],p[2],i===4?0xff7b45:0xffca82,2.2,22);setInterval(()=>{l.intensity=1.4+Math.random()*1.2;},350+i*45);}); this.light(0,4,39,0x8eaeff,2.4,25); const exit=this.addBox(0,2.5,-44,6,5,.6,0x5a0d0d);this.doors.exit={mesh:exit,open:false}; }
  createItems(){ [{x:-30,z:-15,t:'mansion_key',n:'West Wing Key',i:'🗝️'},{x:28,z:-16,t:'fuse',n:'Generator Fuse',i:'⚡'},{x:-29,z:-39,t:'battery',n:'Flashlight Battery',i:'🔋'},{x:25,z:-39,t:'portrait',n:'Burned Portrait',i:'🖼️'},{x:0,z:-22,t:'medkit',n:'First Aid',i:'💊'}].forEach(a=>this.items.push(new Item(this.scene,a.x,1,a.z,a.t,a.n,a.i))); }
  createEnemies(){ this.enemies.push(new Enemy(this.scene,-30,-20,'stealth',[{x:-32,z:-10},{x:-32,z:-40}])); this.enemies.push(new Enemy(this.scene,29,-30,'basic',[{x:30,z:-10},{x:30,z:-40}])); const boss=new Enemy(this.scene,0,-38,'boss',[{x:-8,z:-38},{x:8,z:-38}]);boss.deactivate();this.enemies.push(boss); }
  collide(pos){return pos.x<-37||pos.x>37||pos.z<-42||pos.z>42;}
  bindUI(){ addEventListener('keydown',e=>{this.input.keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')this.interact();if(e.key==='Escape')this.pause();}); addEventListener('keyup',e=>this.input.keys[e.key.toLowerCase()]=false); addEventListener('mousemove',e=>{if(document.pointerLockElement===document.getElementById('game-canvas')&&this.isGameActive&&!this.isPaused){this.camera.rotation.y-=e.movementX*.0018;this.camera.rotation.x=Math.max(-1.2,Math.min(1.2,this.camera.rotation.x-e.movementY*.0018));}}); addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);}); document.getElementById('btn-new-game')?.addEventListener('click',()=>this.start()); document.getElementById('btn-continue')?.addEventListener('click',()=>this.start()); document.getElementById('btn-pause')?.addEventListener('click',()=>this.pause()); document.getElementById('btn-resume')?.addEventListener('click',()=>this.pause()); document.getElementById('btn-main-menu')?.addEventListener('click',()=>this.menu()); document.getElementById('btn-save-game')?.addEventListener('click',()=>this.save()); }
  start(){document.getElementById('main-menu').hidden=true;document.getElementById('game-container').hidden=false;this.player.setPosition(0,1.7,28);this.camera.position.copy(this.player.mesh.position);this.isGameActive=true;document.getElementById('game-canvas').requestPointerLock();}
  pause(){if(!this.isGameActive)return;this.isPaused=!this.isPaused;document.getElementById('pause-menu').hidden=!this.isPaused;if(this.isPaused)document.exitPointerLock();else document.getElementById('game-canvas').requestPointerLock();}
  menu(){this.isGameActive=false;this.isPaused=false;document.exitPointerLock();document.getElementById('game-container').hidden=true;document.getElementById('pause-menu').hidden=true;document.getElementById('main-menu').hidden=false;}
  interact(){if(!this.isGameActive)return;this.items.forEach(it=>{if(!it.isCollected&&this.player.mesh.position.distanceTo(it.mesh.position)<2.3){const item=it.collect();if(item.type==='medkit')this.player.heal(45);else this.player.addToInventory(item);}});if(this.player.hasItem('mansion_key')&&this.player.hasItem('fuse')&&this.player.hasItem('battery')){this.doors.exit.open=true;this.doors.exit.mesh.position.y=8;document.getElementById('objective-text').textContent='Die Eingangstür ist offen. RENNE!';this.enemies[2].activate();}}
  save(){try{SaveSystem.saveToLocal({position:this.player.getPosition(),health:this.player.health,inventory:this.player.inventory});}catch(e){}}
  update(dt){if(!this.isGameActive||this.isPaused)return;const before=this.player.mesh.position.clone();this.player.update(dt,this.input,this.camera,this.enemies);if(this.collide(this.player.mesh.position))this.player.mesh.position.copy(before);this.camera.position.copy(this.player.mesh.position);this.enemies.forEach(e=>e.update(dt,this.player));this.items.forEach(i=>i.update(dt,performance.now()/1000));if(this.player.isDead){this.isGameActive=false;document.exitPointerLock();document.getElementById('death-screen').hidden=false;}if(this.doors.exit.open&&this.player.mesh.position.z<-41){this.isGameActive=false;document.getElementById('victory-screen').hidden=false;}this.hud();}
  hud(){const p=this.player;document.getElementById('health-fill').style.width=p.health+'%';document.getElementById('health-text').textContent=Math.round(p.health)+'%';document.getElementById('stamina-fill').style.width=p.stamina+'%';document.getElementById('stamina-text').textContent=Math.round(p.stamina)+'%';document.getElementById('sanity-fill').style.width=p.sanity+'%';document.getElementById('sanity-text').textContent='SANITY '+Math.round(p.sanity)+'%';}
  animate(){requestAnimationFrame(()=>this.animate());const now=performance.now(),dt=Math.min(.05,(now-this.lastTime)/1000);this.lastTime=now;this.update(dt);if(this.renderer)this.renderer.render(this.scene,this.camera);}
}
window.addEventListener('load',()=>{window.game=new Game();});
